name: "neuralfp"
platform: "pytorch_libtorch"
max_batch_size: 0
input [
    {
        name: "input"
        data_type: TYPE_FP32
        dims: [-1, 256, 32]
    }
]
output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [-1]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]

dynamic_batching {
    max_queue_delay_microseconds: 200
}
